version: '3.8'

services:
  api:
    build: ./api-principal
    ports:
      - "8080:8080"
    networks:
      - meadota-net
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  match:
    build: ./match
    ports:
      - "9000:9000"
    networks:
      - meadota-net
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

  frontend:
    build: ./Frontend
    ports:
      - "8081:8081"
      - "19000:19000"  # Expo DevTools
      - "19001:19001"  # Expo Metro Bundler
      - "19002:19002"  # Expo tunnel
    stdin_open: true
    tty: true
    environment:
      - EXPO_DEVTOOLS_LISTEN_ADDRESS=0.0.0.0
      - REACT_NATIVE_PACKAGER_HOSTNAME=0.0.0.0
    networks:
      - meadota-net
    depends_on:
      api:
        condition: service_healthy
      match:
        condition: service_healthy

networks:
  meadota-net:
    driver: bridge