/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/Cadastrar`; params?: Router.UnknownInputParams; } | { pathname: `/CadastrarPet`; params?: Router.UnknownInputParams; } | { pathname: `/Explorar`; params?: Router.UnknownInputParams; } | { pathname: `/Favoritos`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/Login`; params?: Router.UnknownInputParams; } | { pathname: `/PerfilPet`; params?: Router.UnknownInputParams; } | { pathname: `/../src/Screens/PerfilDeUsuarioScreen`; params?: Router.UnknownInputParams; } | { pathname: `/PerfilDeUsuario`; params?: Router.UnknownInputParams; } | { pathname: `/../src/components/FooterNav`; params?: Router.UnknownInputParams; } | { pathname: `/../src/Components/Footer`; params?: Router.UnknownInputParams; } | { pathname: `/../src/Components/FooterNav`; params?: Router.UnknownInputParams; } | { pathname: `/../src/Screens/TelaDetalhesPet`; params?: Router.UnknownInputParams; } | { pathname: `/MeusPets`; params?: Router.UnknownInputParams; } | { pathname: `/../src/Screens/MeusPetsScreen`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/bellowTab/Favoritos`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/Cadastrar`; params?: Router.UnknownOutputParams; } | { pathname: `/CadastrarPet`; params?: Router.UnknownOutputParams; } | { pathname: `/Explorar`; params?: Router.UnknownOutputParams; } | { pathname: `/Favoritos`; params?: Router.UnknownOutputParams; } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/Login`; params?: Router.UnknownOutputParams; } | { pathname: `/PerfilPet`; params?: Router.UnknownOutputParams; } | { pathname: `/../src/Screens/PerfilDeUsuarioScreen`; params?: Router.UnknownOutputParams; } | { pathname: `/PerfilDeUsuario`; params?: Router.UnknownOutputParams; } | { pathname: `/../src/components/FooterNav`; params?: Router.UnknownOutputParams; } | { pathname: `/../src/Components/Footer`; params?: Router.UnknownOutputParams; } | { pathname: `/../src/Components/FooterNav`; params?: Router.UnknownOutputParams; } | { pathname: `/../src/Screens/TelaDetalhesPet`; params?: Router.UnknownOutputParams; } | { pathname: `/MeusPets`; params?: Router.UnknownOutputParams; } | { pathname: `/../src/Screens/MeusPetsScreen`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `/bellowTab/Favoritos`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/Cadastrar${`?${string}` | `#${string}` | ''}` | `/CadastrarPet${`?${string}` | `#${string}` | ''}` | `/Explorar${`?${string}` | `#${string}` | ''}` | `/Favoritos${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `/Login${`?${string}` | `#${string}` | ''}` | `/PerfilPet${`?${string}` | `#${string}` | ''}` | `/../src/Screens/PerfilDeUsuarioScreen${`?${string}` | `#${string}` | ''}` | `/PerfilDeUsuario${`?${string}` | `#${string}` | ''}` | `/../src/components/FooterNav${`?${string}` | `#${string}` | ''}` | `/../src/Components/Footer${`?${string}` | `#${string}` | ''}` | `/../src/Components/FooterNav${`?${string}` | `#${string}` | ''}` | `/../src/Screens/TelaDetalhesPet${`?${string}` | `#${string}` | ''}` | `/MeusPets${`?${string}` | `#${string}` | ''}` | `/../src/Screens/MeusPetsScreen${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `/bellowTab/Favoritos${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/Cadastrar`; params?: Router.UnknownInputParams; } | { pathname: `/CadastrarPet`; params?: Router.UnknownInputParams; } | { pathname: `/Explorar`; params?: Router.UnknownInputParams; } | { pathname: `/Favoritos`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/Login`; params?: Router.UnknownInputParams; } | { pathname: `/PerfilPet`; params?: Router.UnknownInputParams; } | { pathname: `/../src/Screens/PerfilDeUsuarioScreen`; params?: Router.UnknownInputParams; } | { pathname: `/PerfilDeUsuario`; params?: Router.UnknownInputParams; } | { pathname: `/../src/components/FooterNav`; params?: Router.UnknownInputParams; } | { pathname: `/../src/Components/Footer`; params?: Router.UnknownInputParams; } | { pathname: `/../src/Components/FooterNav`; params?: Router.UnknownInputParams; } | { pathname: `/../src/Screens/TelaDetalhesPet`; params?: Router.UnknownInputParams; } | { pathname: `/MeusPets`; params?: Router.UnknownInputParams; } | { pathname: `/../src/Screens/MeusPetsScreen`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/bellowTab/Favoritos`; params?: Router.UnknownInputParams; };
    }
  }
}
