/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/Login`; params?: Router.UnknownInputParams; } | { pathname: `/login`; params?: Router.UnknownInputParams; } | { pathname: `/CadastrarPet`; params?: Router.UnknownInputParams; } | { pathname: `/pets`; params?: Router.UnknownInputParams; } | { pathname: `/bellowTab/Favoritos`; params?: Router.UnknownInputParams; } | { pathname: `/Favoritos`; params?: Router.UnknownInputParams; } | { pathname: `/Cadastrar`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/Login`; params?: Router.UnknownOutputParams; } | { pathname: `/login`; params?: Router.UnknownOutputParams; } | { pathname: `/CadastrarPet`; params?: Router.UnknownOutputParams; } | { pathname: `/pets`; params?: Router.UnknownOutputParams; } | { pathname: `/bellowTab/Favoritos`; params?: Router.UnknownOutputParams; } | { pathname: `/Favoritos`; params?: Router.UnknownOutputParams; } | { pathname: `/Cadastrar`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/${`?${string}` | `#${string}` | ''}` | `/Login${`?${string}` | `#${string}` | ''}` | `/login${`?${string}` | `#${string}` | ''}` | `/CadastrarPet${`?${string}` | `#${string}` | ''}` | `/pets${`?${string}` | `#${string}` | ''}` | `/bellowTab/Favoritos${`?${string}` | `#${string}` | ''}` | `/Favoritos${`?${string}` | `#${string}` | ''}` | `/Cadastrar${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/Login`; params?: Router.UnknownInputParams; } | { pathname: `/login`; params?: Router.UnknownInputParams; } | { pathname: `/CadastrarPet`; params?: Router.UnknownInputParams; } | { pathname: `/pets`; params?: Router.UnknownInputParams; } | { pathname: `/bellowTab/Favoritos`; params?: Router.UnknownInputParams; } | { pathname: `/Favoritos`; params?: Router.UnknownInputParams; } | { pathname: `/Cadastrar`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; };
    }
  }
}
