CREATE TABLE IF NOT EXISTS Usuario (
    Id_usuario INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Nome VARCHAR(100) NOT NULL,
    Telefone VARCHAR(20),
    Email VARCHAR(100) NOT NULL UNIQUE,
    Senha_hash VARCHAR(255) NOT NULL,
    Data_cadastro TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    Tipo VARCHAR(20) NOT NULL,
    CHECK (Tipo IN ('Adotante', 'Protetor', 'ONG'))
);

CREATE TABLE IF NOT EXISTS HistoricoUsuario (
    Id_historico_usuario INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Id_usuario INT NOT NULL,
    Mensagem CLOB,
    Data TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (Id_usuario) REFERENCES Usuario(Id_usuario) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS Pet (
    Id_pet INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Id_usuario INT NOT NULL,
    Nome VARCHAR(100) NOT NULL,
    Especie VARCHAR(50) NOT NULL,
    Idade INT,
    Porte VARCHAR(20),
    Peso DOUBLE,
    Sexo CHAR(1) CHECK (Sexo IN ('M', 'F', 'O')),
    Bio CLOB,
    Fotos BLOB,
    FOREIGN KEY (Id_usuario) REFERENCES Usuario(Id_usuario)
);

CREATE TABLE IF NOT EXISTS HistoricoMedicoPet (
    Id_historico_medico_pet INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Id_pet INT NOT NULL,
    Hospital VARCHAR(100),
    Resultado CLOB,
    Tratamento CLOB,
    Documento VARCHAR(255),
    Data DATE,
    FOREIGN KEY (Id_pet) REFERENCES Pet(Id_pet) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS Adocao (
    Id_adocao INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Id_pet INT NOT NULL,
    Id_adotante INT NOT NULL,
    Status VARCHAR(20) NOT NULL,
    CHECK (Status IN ('Pendente', 'Aceita', 'Rejeitada', 'Finalizada')),
    FOREIGN KEY (Id_pet) REFERENCES Pet(Id_pet),
    FOREIGN KEY (Id_adotante) REFERENCES Usuario(Id_usuario)
);

CREATE TABLE IF NOT EXISTS HistoricoAdocao (
    Id_historico_adocao INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Id_adocao INT NOT NULL,
    Id_treinador INT NOT NULL,
    Data TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (Id_adocao) REFERENCES Adocao(Id_adocao) ON DELETE CASCADE,
    FOREIGN KEY (Id_treinador) REFERENCES Usuario(Id_usuario)
);

CREATE TABLE IF NOT EXISTS Categorias (
    Id_categoria INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Nome VARCHAR(50) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS Tags (
    Id_tag INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Nome VARCHAR(50) NOT NULL,
    Id_categoria INT,
    FOREIGN KEY (Id_categoria) REFERENCES Categorias(Id_categoria) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS TagsPet (
    Id_pet INT NOT NULL,
    Id_tag INT NOT NULL,
    PRIMARY KEY (Id_pet, Id_tag),
    FOREIGN KEY (Id_pet) REFERENCES Pet(Id_pet) ON DELETE CASCADE,
    FOREIGN KEY (Id_tag) REFERENCES Tags(Id_tag) ON DELETE CASCADE
);