CREATE TABLE IF NOT EXISTS usuario (
    Id_usuario BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Nome VARCHAR(100) NOT NULL,
    Telefone VARCHAR(20),
    Email VARCHAR(100) NOT NULL UNIQUE,
    Senha_hash VARCHAR(255) NOT NULL,
    Data_cadastro TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    Tipo VARCHAR(20) NOT NULL,
    CHECK (Tipo IN ('PESSOA', 'ONG')),
    Perfil_usuario   VARCHAR(20) NOT NULL,
    CHECK (Perfil_usuario IN ('ADOTANTE', 'PROTETOR', 'AMBOS'))
);

CREATE TABLE IF NOT EXISTS historico_usuario (
    Id_historico_usuario BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Id_usuario BIGINT NOT NULL,
    Mensagem CLOB,
    Data TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (Id_usuario) REFERENCES usuario(Id_usuario) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS pet (
    Id_pet BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Id_usuario BIGINT NOT NULL,
    Nome VARCHAR(100) NOT NULL,
    Especie VARCHAR(50) NOT NULL,
    Raca VARCHAR(70) NOT NULL,
    Idade INT,
    Porte VARCHAR(20),
    Peso DOUBLE,
    Sexo CHAR(1) CHECK (Sexo IN ('M', 'F', 'O')),
    Bio CLOB,
    Fotos BLOB,
    FOREIGN KEY (Id_usuario) REFERENCES usuario(Id_usuario)
);

CREATE TABLE IF NOT EXISTS historico_medico_pet (
    Id_historico_medico_pet BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Id_pet BIGINT NOT NULL,
    Hospital VARCHAR(100),
    Resultado CLOB,
    Tratamento CLOB,
    Documento VARCHAR(255),
    Data DATE,
    FOREIGN KEY (Id_pet) REFERENCES pet(Id_pet) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS adocao (
    Id_adocao BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Id_pet BIGINT NOT NULL,
    Id_adotante BIGINT NOT NULL,
    Status VARCHAR(20) NOT NULL,
    CHECK (Status IN ('Adotado', 'Falecido', 'Disponivel', 'Disponível', 'Perdido')),
    FOREIGN KEY (Id_pet) REFERENCES pet(Id_pet),
    FOREIGN KEY (Id_adotante) REFERENCES usuario(Id_usuario)
);

CREATE TABLE IF NOT EXISTS historico_adocao (
    Id_historico_adocao BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Id_adocao BIGINT NOT NULL,
    Id_protetor BIGINT NOT NULL,
    Data TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (Id_adocao) REFERENCES adocao(Id_adocao) ON DELETE CASCADE,
    FOREIGN KEY (Id_protetor) REFERENCES usuario(Id_usuario)
);

CREATE TABLE IF NOT EXISTS categorias (
    Id_categoria BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Nome VARCHAR(50) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS tags (
    Id_tag BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Nome VARCHAR(50) NOT NULL,
    Id_categoria BIGINT,
    FOREIGN KEY (Id_categoria) REFERENCES categorias(Id_categoria) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS tags_pet (
    Id_pet BIGINT NOT NULL,
    Id_tag BIGINT NOT NULL,
    PRIMARY KEY (Id_pet, Id_tag),
    FOREIGN KEY (Id_pet) REFERENCES pet(Id_pet) ON DELETE CASCADE,
    FOREIGN KEY (Id_tag) REFERENCES tags(Id_tag) ON DELETE CASCADE
);